#! /bin/bash
set -euo pipefail

OUTPUT_COLORSPACE_DIR="$TEST_OUTPUT_DIR/$1"

mkdir -p $OUTPUT_COLORSPACE_DIR

$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png -type grayscale "$OUTPUT_COLORSPACE_DIR/$TEST_SAMPLE_RGBY-gray.png"
$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png -type grayscale "$OUTPUT_COLORSPACE_DIR/$TEST_SAMPLE_RGBY-gray.jpg"

$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png "$OUTPUT_COLORSPACE_DIR/$TEST_SAMPLE_RGBY-rgb.png"
$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png "$OUTPUT_COLORSPACE_DIR/$TEST_SAMPLE_RGBY-rgb.jpg"

$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png -colorspace CMYK "$OUTPUT_COLORSPACE_DIR/$TEST_SAMPLE_RGBY-cmyk.jpg"
