#! /bin/bash
set -euo pipefail

IM_CONV=convert

SAMPLE_RGBY=$1 ; OUTPUT_DIR=$2 ; OUTPUT_COLORSPACE_DIR="$2/$3"
mkdir -p $OUTPUT_COLORSPACE_DIR

$IM_CONV $OUTPUT_DIR/$SAMPLE_RGBY.png -type grayscale "$OUTPUT_COLORSPACE_DIR/$SAMPLE_RGBY-gray.png"
$IM_CONV $OUTPUT_DIR/$SAMPLE_RGBY.png -type grayscale "$OUTPUT_COLORSPACE_DIR/$SAMPLE_RGBY-gray.jpg"

$IM_CONV $OUTPUT_DIR/$SAMPLE_RGBY.png "$OUTPUT_COLORSPACE_DIR/$SAMPLE_RGBY-rgb.png"
$IM_CONV $OUTPUT_DIR/$SAMPLE_RGBY.png "$OUTPUT_COLORSPACE_DIR/$SAMPLE_RGBY-rgb.jpg"

$IM_CONV $OUTPUT_DIR/$SAMPLE_RGBY.png -colorspace CMYK "$OUTPUT_COLORSPACE_DIR/$SAMPLE_RGBY-cmyk.jpg"
