#! /bin/bash
set -euo pipefail

OUTPUT_INTERLACE_DIR="$TEST_OUTPUT_DIR/$1"

mkdir -p $OUTPUT_INTERLACE_DIR

$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png -interlace JPEG \
            "$OUTPUT_INTERLACE_DIR/${TEST_SAMPLE_RGBY}-prog.jpg"
$IM_CONVERT $TEST_OUTPUT_DIR/$TEST_SAMPLE_RGBY.png -interlace PNG \
            "$OUTPUT_INTERLACE_DIR/${TEST_SAMPLE_RGBY}-inter.png"
